query searchRepo($quantity: Number, $after: String, $query: string) {
    search(first: $quantity, after: $after, query: $query, type: REPOSITORY) {
        ...SearchResultFields
        repositoryCount
        pageInfo {
            endCursor
            hasNextPage
        }
    }
}

fragment SearchResultFields on SearchResultItemConnection {
    nodes {
        ... on Repository {
            nameWithOwner
            description
            url
            forkCount
            object(expression: "master") {
                ... on Commit {
                    history {
                        totalCount
                    }
                }
            }
            issues(states: OPEN) {
                totalCount
            }
            pullRequests(states: OPEN) {
                totalCount
            }
            stargazers {
                totalCount
            }
        }
    }
}

fragment SearchResultFields on SearchResultItemConnection {
    nodes {
        ... on User {
            avatarUrl
            pullRequests(
                first: 100
                states: [OPEN, MERGED]
                orderBy: { field: CREATED_AT, direction: DESC }
            ) {
                nodes {
                    title
                    createdAt
                    closed
                    merged
                    mergedAt
                    state
                    repository {
                        name
                        owner {
                            login
                        }
                    }
                }
            }
        }
    }
}
